# Generated by Django 5.1.6 on 2025-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="business_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="business_place_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="google_review_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
