# Generated by Django 5.1.6 on 2025-08-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_auto_20250811_2057"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="business_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
